stages:
  - build
  - test
  - publish

variables:
  CONTAINER_NAME: "namespace/project"
  CONTAINER_REGISTRY: "https://index.docker.io/v1/"
  CONTAINER_REGISTRY_USER: ""
  CONTAINER_REGISTRY_PASSWORD: ""

include:
  - project: 'devops/gitlab-ci-templates'
    file:
      - 'drupal.yml'

build:hub:
  extends: .build_docker
  only:
    - main
    - tags
  before_script:
    - echo "{\"auths\":{\"$CONTAINER_REGISTRY\":{\"username\":\"$CONTAINER_REGISTRY_USER\",\"password\":\"$CONTAINER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - chmod -R g-w,o-w .
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then TAG="latest"; else TAG=$CI_COMMIT_REF_NAME; fi
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CONTAINER_NAME:$CI_COMMIT_TAG --destination $CONTAINER_NAME:latest
