---
version: '3'

services:
  drupal:
    build: ./
    image: openculturas/openculturas:latest
    container_name: drupal
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/web
      DRUPAL_PROJECT_ROOT: /var/www/html
      DRUPAL_PROJECT_VERSION: dev-main
      DRUPAL_DATABASE_HOST: drupal-mysql
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_PREFIX: drupal_
      # Generate a salt with: `php -r "echo bin2hex(random_bytes(25));"`
      DRUPAL_HASH_SALT: db0de8a1556aa5348f87cfc950cd2c9641713d46e9412c8b05
    ports:
      - "80:80"
    restart: always
    # Uncomment the volumes line and set to the local path of your Drupal
    # installation, if you need to work with a local codebase.
    # volumes:
    #   - ~/Sites/drupal-container:/var/www/html:rw,delegated

  mysql:
    image: mariadb:10
    container_name: drupal-mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    ports:
      - "3306:3306"
